//! Native, continuously drained evidence from the resident Inkling runtime.
//!
//! These fragments are exhaust of ordinary model operation, not an export
//! format. `Ready` and `TurnEnd` are still serializable values, but nothing
//! transmits them any more — the model is in this process — and the durable
//! observation surface was never the wire in the first place: it is typed
//! Trible facts emitted through `drive::mind::Mind::take_exhaust`. Each entity is intrinsic: equal READY
//! announcements and equal turn measurements collapse naturally, while Drive
//! links their exported roots to the runtime session and the turn that caused
//! them.
//!
//! Stable ids below were minted with `trible genid` on 2026-08-28. Their
//! provenance is also recorded in the commits that introduced them.

use anyhow::{Context as _, Result};
use triblespace::core::metadata;
use triblespace::prelude::blobencodings::UTF8String;
use triblespace::prelude::inlineencodings::{Blake3, Boolean, F64, Handle, Hash, U256BE};
use triblespace::prelude::*;

use super::resident::{ContextPlacement, ContextPreflighted, Ready, Reinitialized, TurnEnd};

/// Query vocabulary for Inkling's native runtime evidence.
pub mod schema {
    use super::*;

    attributes! {
        /// Canonical identity of the projected model facts actually loaded.
        /// Minted 2026-08-28: E65EDFF32D71BAB66F6B1BA69C11ABE3.
        "E65EDFF32D71BAB66F6B1BA69C11ABE3" as pub model_identity: Hash<Blake3>;
        /// Content identity of the exact tokenizer bytes.
        /// Minted 2026-08-28: 01C84FAC727F47AF438951439ED3B657.
        "01C84FAC727F47AF438951439ED3B657" as pub tokenizer_identity: Hash<Blake3>;
        /// Identity of the sealed/observed executable configuration.
        /// Minted 2026-08-28: 45514D5DD40BA7A83A84A6F9C829D66A.
        "45514D5DD40BA7A83A84A6F9C829D66A" as pub execution_identity: Hash<Blake3>;
        /// Runtime compatibility profile, carried as text because the protocol
        /// may grow profiles longer than the inline-string ceiling.
        /// Minted 2026-08-28: 5D90F16E9D15FB0593A569ECBA0F60D6.
        "5D90F16E9D15FB0593A569ECBA0F60D6" as pub execution_profile: Handle<UTF8String>;
        /// One runtime fact the execution digest could not observe. Repeated.
        /// Minted 2026-08-28: 33E1242230043B3C0888E441A5D9A065.
        "33E1242230043B3C0888E441A5D9A065" as pub execution_unavailable: Handle<UTF8String>;
        /// Tensor-parallel world width.
        /// Minted 2026-08-28: 15E5022076B6FCD2D8A75A46F63632BD.
        "15E5022076B6FCD2D8A75A46F63632BD" as pub tp_world: U256BE;
        /// Inclusive first layer executed by this runtime.
        /// Minted 2026-08-28: 19E89699A3E9FB306605B5D606DDD4C6.
        "19E89699A3E9FB306605B5D606DDD4C6" as pub layer_start: U256BE;
        /// Exclusive layer bound executed by this runtime.
        /// Minted 2026-08-28: 58B5658209F34A7DD2DE2A0B3A800F98.
        "58B5658209F34A7DD2DE2A0B3A800F98" as pub layer_end: U256BE;
        /// Layer count in the complete model stack.
        /// Minted 2026-08-28: 03B14702AFAC0CAC05A18E53E22DE43E.
        "03B14702AFAC0CAC05A18E53E22DE43E" as pub stack_layers: U256BE;
        /// Whether the runtime executes only a diagnostic subrange.
        /// Minted 2026-08-28: 687C4ECA472A07028A0F7D59AE0BFEA7.
        "687C4ECA472A07028A0F7D59AE0BFEA7" as pub partial: Boolean;
        /// Effective vocabulary width.
        /// Minted 2026-08-28: 01DDA41F5400CD67D95682BC9E25B6CC.
        "01DDA41F5400CD67D95682BC9E25B6CC" as pub vocabulary_width: U256BE;
        /// Maximum token rows processed by one prefill pass.
        /// Minted 2026-08-28: 3CEAC9AFF36E1CE08D2DA2BE737A2727.
        "3CEAC9AFF36E1CE08D2DA2BE737A2727" as pub prefill_budget: U256BE;
        /// Maximum positions retained by the resident session.
        /// Minted 2026-08-28: 76667F930CB5681FF1C7B576110F3B51.
        "76667F930CB5681FF1C7B576110F3B51" as pub context_budget: U256BE;
        /// Wall-clock seconds spent loading the resident session.
        /// Minted 2026-08-28: BCCFAEF674B2A98F85DF6D41B76D04C0.
        "BCCFAEF674B2A98F85DF6D41B76D04C0" as pub load_seconds: F64;
        /// Logical turn ordinal on this resident session.
        /// Minted 2026-08-28: 27A9341F1C0B04E027B8AAFEE6239D3F.
        "27A9341F1C0B04E027B8AAFEE6239D3F" as pub turn: U256BE;
        /// Tokens generated by the complete logical turn.
        /// Minted 2026-08-28: 74A96268D9691166BD173661CD8C94B7.
        "74A96268D9691166BD173661CD8C94B7" as pub generated_tokens: U256BE;
        /// Fresh delta tokens attended before generation.
        /// Minted 2026-08-28: 1E2CFE6D0F59911803B5FA39AAFDBE39.
        "1E2CFE6D0F59911803B5FA39AAFDBE39" as pub delta_tokens: U256BE;
        /// Tokens carried from the model's previous turn.
        /// Minted 2026-08-28: 80F7AB2F034F53FE82C0D5242258205B.
        "80F7AB2F034F53FE82C0D5242258205B" as pub carried_tokens: U256BE;
        /// Why generation stopped, as the mind judged it.
        /// Minted 2026-08-28: 6A54094F008D8C05CEC807CF1F3E321A.
        "6A54094F008D8C05CEC807CF1F3E321A" as pub stop_reason: Handle<UTF8String>;
        /// Seconds to the first token of this turn, around the Session calls.
        /// Minted 2026-08-28: F8CF2A5C82EA89682E45F85BCA08E2A1.
        "F8CF2A5C82EA89682E45F85BCA08E2A1" as pub first_token_seconds: F64;
        /// Sum, in nats, of the negative log-likelihood the model assigned the
        /// scored delta tokens of a turn before it had seen them (the
        /// prequential score); with `delta_scored_tokens` it totals across
        /// turns and sessions, which a mean would not.
        /// Minted 2026-09-03: 52A8E8632A14B913CA2B11875B20DDD9.
        "52A8E8632A14B913CA2B11875B20DDD9" as pub delta_nll_nats: F64;
        /// How many delta tokens `delta_nll_nats` sums over.
        /// Minted 2026-09-03: F7157BAA97382DCCB5D75AF8D3263B2F.
        "F7157BAA97382DCCB5D75AF8D3263B2F" as pub delta_scored_tokens: U256BE;
        /// Seconds for the complete logical turn, around the Session calls.
        /// Minted 2026-08-28: 379776AE923C962A7DE2A6DBC03DA77F.
        "379776AE923C962A7DE2A6DBC03DA77F" as pub turn_seconds: F64;
        /// Positions retained in the KV cache after the turn.
        /// Minted 2026-08-28: 42DB94B3C5C091BC292D5B8FFB56E759.
        "42DB94B3C5C091BC292D5B8FFB56E759" as pub position: U256BE;
        /// Whether admission extends or replaces the resident context.
        /// Minted 2026-08-28: 837E12BA128DA953C58A083BCB2A9B30.
        "837E12BA128DA953C58A083BCB2A9B30" as pub context_placement: Handle<UTF8String>;
        /// Complete response width reserved by context admission.
        /// Minted 2026-08-28: 56DB15A2503039E81A5FD709F91DCDEA.
        "56DB15A2503039E81A5FD709F91DCDEA" as pub max_response_tokens: U256BE;
        /// Exclusive position required by the admitted context and response.
        /// Absent when checked arithmetic overflowed.
        /// Minted 2026-08-28: 880D7D9E72D0095AC2D71FEE7714F7E5.
        "880D7D9E72D0095AC2D71FEE7714F7E5" as pub required_end: U256BE;
        /// Whether the complete operation fits the resident context budget.
        /// Minted 2026-08-28: B04E876F833D7B8ABD067098AD01A38E.
        "B04E876F833D7B8ABD067098AD01A38E" as pub fits: Boolean;
        /// Position discarded by a successfully acknowledged reinitialization.
        /// Minted 2026-08-28: 4063D646983C74B47DD6F9610BC6895F.
        "4063D646983C74B47DD6F9610BC6895F" as pub previous_position: U256BE;
        /// Completed turns discarded by an acknowledged reinitialization.
        /// Minted 2026-08-28: F45396CD0A59B6CD5C2F5B70511754D0.
        "F45396CD0A59B6CD5C2F5B70511754D0" as pub previous_turns: U256BE;
        /// Tokens staged for the replacement context.
        /// Minted 2026-08-28: 7785C75EE5323CAF9891A0E32ACFD1B2.
        "7785C75EE5323CAF9891A0E32ACFD1B2" as pub initialization_tokens: U256BE;
        /// Resident context epoch installed by the acknowledged replacement.
        /// Minted 2026-08-28: D650C79F1FC0FE6ACE0E4EA85050DB7F.
        "D650C79F1FC0FE6ACE0E4EA85050DB7F" as pub context_epoch: U256BE;
    }

    /// A READY announcement from a loaded resident runtime.
    /// Minted 2026-08-28: FA70B386BACF9584B2DB9855C1296A97.
    #[allow(non_upper_case_globals)]
    pub const kind_ready: Id = triblespace::macros::id_hex!("FA70B386BACF9584B2DB9855C1296A97");

    /// One completed logical model turn.
    /// Minted 2026-08-28: 393BFF0B7490738059AAE5440B5DBBAB.
    #[allow(non_upper_case_globals)]
    pub const kind_turn_end: Id = triblespace::macros::id_hex!("393BFF0B7490738059AAE5440B5DBBAB");

    /// One exact context-admission preflight.
    /// Minted 2026-08-28: EFEE37F606721308DD306D1A02711294.
    #[allow(non_upper_case_globals)]
    pub const kind_context_preflight: Id =
        triblespace::macros::id_hex!("EFEE37F606721308DD306D1A02711294");

    /// One successfully acknowledged warm-context reinitialization.
    /// Minted 2026-08-28: 105FB0A444658DEC45333B1BF14AC63D.
    #[allow(non_upper_case_globals)]
    pub const kind_reinitialized: Id =
        triblespace::macros::id_hex!("105FB0A444658DEC45333B1BF14AC63D");
}

/// Turn one validated READY announcement into a self-contained native fragment.
///
/// Identities are deliberately parsed as BLAKE3 values rather than retained as
/// strings. A malformed wire announcement therefore fails construction at the
/// mind boundary instead of becoming an unqueryable or silently missing fact.
pub fn ready_fragment(ready: &Ready) -> Result<Fragment> {
    let model_identity = Hash::<Blake3>::from_hex(&ready.model_identity)
        .context("READY model identity is not a 32-byte hexadecimal BLAKE3 digest")?;
    let tokenizer_identity = Hash::<Blake3>::from_hex(&ready.tokenizer_identity)
        .context("READY tokenizer identity is not a 32-byte hexadecimal BLAKE3 digest")?;
    let execution_identity = Hash::<Blake3>::from_hex(&ready.execution_identity)
        .context("READY execution identity is not a 32-byte hexadecimal BLAKE3 digest")?;

    let mut fragment = Fragment::empty();
    let execution_profile = fragment.put::<UTF8String, _>(ready.execution_profile.to_owned());
    let execution_unavailable = ready
        .execution_unavailable
        .iter()
        .map(|fact| fragment.put::<UTF8String, _>(fact.to_owned()))
        .collect::<Vec<_>>();

    fragment += entity! { _ @
        metadata::tag: schema::kind_ready,
        schema::model_identity: model_identity,
        schema::tokenizer_identity: tokenizer_identity,
        schema::execution_identity: execution_identity,
        schema::execution_profile: execution_profile,
        schema::execution_unavailable*: execution_unavailable,
        schema::tp_world: ready.tp_world as u128,
        schema::layer_start: ready.layers[0] as u128,
        schema::layer_end: ready.layers[1] as u128,
        schema::stack_layers: ready.stack as u128,
        schema::partial: ready.partial,
        schema::vocabulary_width: ready.vocab as u128,
        schema::prefill_budget: ready.prefill_budget as u128,
        schema::context_budget: ready.context_budget as u128,
        schema::load_seconds: ready.load_secs,
    };
    Ok(fragment)
}

/// Turn one completed logical model turn into a self-contained native fragment.
///
/// Exact token ids stay on the serving wire for lockstep arbitration. The slim
/// continuous slice records the aggregate fields needed to characterize a live
/// turn; an exact token-sequence blob can be added later without changing this
/// entity's existing facts.
pub fn turn_end_fragment(end: &TurnEnd) -> Fragment {
    let mut fragment = Fragment::empty();
    let stop_reason = fragment.put::<UTF8String, _>(end.stopped.to_owned());
    let scored = (!end.delta_nll.is_empty()).then(|| {
        let nats: f64 = end.delta_nll.iter().map(|&x| x as f64).sum();
        (nats, end.delta_nll.len() as u128)
    });
    fragment += entity! { _ @
        metadata::tag: schema::kind_turn_end,
        schema::turn: end.turn as u128,
        schema::generated_tokens: end.tokens as u128,
        schema::delta_tokens: end.delta_tokens as u128,
        schema::carried_tokens: end.carried as u128,
        schema::stop_reason: stop_reason,
        schema::first_token_seconds: end.first_token_secs,
        schema::turn_seconds: end.turn_secs,
        schema::position: end.position as u128,
        schema::delta_nll_nats?: scored.map(|(nats, _)| nats),
        schema::delta_scored_tokens?: scored.map(|(_, count)| count),
    };
    fragment
}

/// Preserve the exact validated arithmetic produced by one context preflight.
pub fn context_preflight_fragment(evidence: &ContextPreflighted) -> Fragment {
    let mut fragment = Fragment::empty();
    let placement = fragment.put::<UTF8String, _>(match evidence.placement {
        ContextPlacement::Append => "append".to_string(),
        ContextPlacement::Replace => "replace".to_string(),
    });
    fragment += entity! { _ @
        metadata::tag: schema::kind_context_preflight,
        schema::context_placement: placement,
        schema::position: evidence.position as u128,
        schema::carried_tokens: evidence.carried as u128,
        schema::delta_tokens: evidence.delta_tokens as u128,
        schema::max_response_tokens: evidence.max_response_tokens as u128,
        schema::required_end?: evidence.required_end.map(|end| end as u128),
        schema::context_budget: evidence.context_budget as u128,
        schema::fits: evidence.fits,
    };
    fragment
}

/// Preserve a warm-context replacement only after the model acknowledged it.
pub fn reinitialized_fragment(next_epoch: u64, acknowledged: &Reinitialized) -> Fragment {
    entity! { _ @
        metadata::tag: schema::kind_reinitialized,
        schema::context_epoch: next_epoch as u128,
        schema::previous_position: acknowledged.previous_position as u128,
        schema::previous_turns: acknowledged.previous_turns as u128,
        schema::initialization_tokens: acknowledged.initialization_tokens as u128,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::inkling::resident::InklingSpecialIds;

    fn ready() -> Ready {
        Ready {
            pile: "fixture.pile".to_string(),
            model_identity: "11".repeat(32),
            tokenizer_identity: "22".repeat(32),
            special_ids: InklingSpecialIds {
                message_model: 1,
                message_system: 2,
                message_tool: 3,
                content_text: 4,
                content_xml: 5,
                content_thinking: 6,
                content_invoke_tool_json: 7,
                content_model_end_sampling: 8,
                end_message: 9,
                all_special: (1..=9).collect(),
                decoded_special: Vec::new(),
            },
            execution_profile: "sealed-v1".to_string(),
            execution_identity: "33".repeat(32),
            execution_unavailable: vec!["cuda-driver-build".to_string()],
            tp_rank: None,
            tp_world: 2,
            layers: [0, 42],
            stack: 42,
            partial: false,
            vocab: 200_058,
            prefill_budget: 1_024,
            context_budget: 32_768,
            load_secs: 12.5,
        }
    }

    #[test]
    fn ready_is_one_rooted_self_contained_native_fragment() {
        let fragment = ready_fragment(&ready()).expect("valid READY");
        let root = fragment.root().expect("READY root");
        let worlds: Vec<u128> = find!(
            world: u128,
            pattern!(&fragment, [{ root @ schema::tp_world: ?world }])
        )
        .collect();
        assert_eq!(worlds, [2]);
        assert!(
            !fragment.blobs().is_empty(),
            "text values travel with facts"
        );
    }

    #[test]
    fn malformed_ready_identity_is_rejected_without_a_panic() {
        let mut malformed = ready();
        malformed.model_identity = "not-a-digest".to_string();
        let error = ready_fragment(&malformed).expect_err("malformed identity must fail");
        assert!(format!("{error:#}").contains("model identity"), "{error:#}");
    }

    #[test]
    fn turn_end_keeps_the_wire_measurements_as_typed_facts() {
        let fragment = turn_end_fragment(&TurnEnd {
            turn: 7,
            tokens: 11,
            token_ids: vec![42; 11],
            delta_tokens: 13,
            delta_nll: vec![2.5, 0.5, 3.0],
            carried: 1,
            stopped: "stop_token".to_string(),
            first_token_secs: 0.25,
            turn_secs: 1.5,
            position: 1_024,
        });
        let root = fragment.root().expect("TurnEnd root");
        let measurements: Vec<(u128, f64)> = find!(
            (tokens: u128, seconds: f64),
            pattern!(&fragment, [{
                root @
                    schema::generated_tokens: ?tokens,
                    schema::turn_seconds: ?seconds
            }])
        )
        .collect();
        assert_eq!(measurements, [(11, 1.5)]);
    }

    #[test]
    fn context_preflight_keeps_exact_admission_arithmetic() {
        let fragment = context_preflight_fragment(&ContextPreflighted {
            placement: ContextPlacement::Replace,
            position: 0,
            carried: 0,
            delta_tokens: 13,
            max_response_tokens: 32,
            required_end: Some(44),
            context_budget: 4_096,
            fits: true,
        });
        let root = fragment.root().expect("preflight root");
        let evidence: Vec<(u128, u128, bool)> = find!(
            (delta: u128, required_end: u128, fits: bool),
            pattern!(&fragment, [{
                root @
                    schema::delta_tokens: ?delta,
                    schema::required_end: ?required_end,
                    schema::fits: ?fits
            }])
        )
        .collect();
        assert_eq!(evidence, [(13, 44, true)]);
    }

    #[test]
    fn reinitialization_ack_names_the_installed_epoch() {
        let fragment = reinitialized_fragment(
            7,
            &Reinitialized {
                previous_position: 1_024,
                previous_turns: 11,
                initialization_tokens: 512,
            },
        );
        let root = fragment.root().expect("reinitialization root");
        let evidence: Vec<(u128, u128)> = find!(
            (epoch: u128, tokens: u128),
            pattern!(&fragment, [{
                root @
                    schema::context_epoch: ?epoch,
                    schema::initialization_tokens: ?tokens
            }])
        )
        .collect();
        assert_eq!(evidence, [(7, 512)]);
    }
}
